name: build
on: [workflow_dispatch]
jobs:
    build:
      permissions:
        contents: read
        packages: write

      runs-on: ubuntu-latest
      steps:
        - name: checkout
          uses: actions/checkout@v6

        - name: setup buf
          uses: bufbuild/buf-action@v1
          with:
            version: 1.66.1
            setup_only: true

        - name: setup java
          uses: actions/setup-java@v6
          with:
            java-version-file: '.sdkmanrc'
            cache: 'maven'
            cache-dependency-path: './src/be/grpc-server/pom.xml'

        - name: maven build
          env:
            REGISTRY_USER: ${{ github.actor }}
            REGISTRY_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          working-directory: './src/be/grpc-server'
          run: |
            mvn compile com.google.cloud.tools:jib-maven-plugin:build \
              -Djib.to.auth.username=$REGISTRY_USER \
              -Djib.to.auth.password=$REGISTRY_TOKEN \
              --batch-mode