name: ci
on: [workflow_dispatch]
jobs:
  ci:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    steps:
      - name: checkout
        uses: actions/checkout@v6

      - name: setup buf
        uses: bufbuild/buf-action@v1
        with:
          version: 1.66.1
          setup_only: true

      - name: setup java
        uses: actions/setup-java@v6
        with:
          java-version-file: '.sdkmanrc'
          cache: 'maven'
          cache-dependency-path: './src/be/grpc-server/pom.xml'

      - name: maven build
        working-directory: './src/be/grpc-server'
        run: |
          mvn \
          --batch-mode \
          --activate-profiles=ci \
          verify

      - name: Scan with trivy
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          image-ref: 'ghcr.io/bigmikecodes/sb-grpc:${{ github.sha }}'
          format: 'sarif'
          output: 'trivy-results.sarif'

      - name: Upload trivy scan results
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: 'trivy-results.sarif'
          category: 'trivy'